auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: BlackRoot.cn
url: http://www.blackroom.cn
feed: /atom.xml
author_info: <a href="http://www.blackroom.cn/">BLACKROOM</a>
